import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import Nav from '@/components/home/navbar/nav';
import { DarkModeProvider } from '@/providers/darkModeProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <DarkModeProvider>
          <Nav />
          <div className="dark:bg-gray-800 flex-1">{children}</div>
        </DarkModeProvider>
      </body>
    </html>
  );
}
